# 🧶 Intensivo Curso Ada Tech: Data Science.

<img src="ada.svg" width="200rem">

**Bibliotecas Utilizadas:**
> 🐼 pandas para manipulação e análise de dados tabulares. Doc: https://bit.ly/46BOzo6

> 0️⃣ numpy para funções e operações matemáticas de alto desempenho. Doc: https://bit.ly/3PJGRRK

> 🤖 scikit-learn para aprendizado de máquina e que fornece ferramentas para treinar modelos.

> 📊 matplotlib para criação de gráficos e visualização de dados.

In [42]:
import pandas as pd
import numpy as np
import sklearn as sk
import matplotlib as plt

## Introdução ao Numpy:

In [2]:
# Arrays: Estrutura de dados.

listanumerica = [1, 2, 3, 4, 5]
listaArrayNumpy = np.array(listanumerica) # A lista torna-se um Array do numpy

In [3]:
print(listanumerica)
print(listaArrayNumpy)

[1, 2, 3, 4, 5]
[1 2 3 4 5]


In [4]:
# Matrizes: Grade de valores.

matrizes_np = np.zeros((4, 5)) 
print(matrizes_np)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [20]:
# Cálculo de estatísticas das notas (Max, Min e Média)

lista_notas1 = [6.7, 5.8, 8.2, 6.0, 3.4]
notas1 = np.array(lista_notas1)

print(f"Nota máxima: {notas1.max()}") 
print(f"Nota mínimo: {notas1.min()}")
print(f"Nota média: {notas1.mean()}")

print(f"Posição da menor nota na Array: {notas1.argmin()}")
print(f"Desvio padrão: {notas1.std()}")

Nota máxima: 8.2
Nota mínimo: 3.4
Nota média: 6.02
Posição da menor nota na Array: 4
Desvio padrão: 1.5574337867145427


###  • Máscara Booleana:
> ❓ Usada para filtrar ou selecionar elementos em um conjunto de dados. Aplicar condições lógicas, como "verdadeiro" ou "falso", em elementos individuais de um conjunto, permitindo que você escolha quais elementos deseja incluir ou excluir com base nessas condições.

In [49]:
covid = np.array(['Yes', 'No', 'Yes', 'No', 'Yes', 'No'])

maskcovid_yes = covid == 'Yes'

covid[maskcovid_yes] = 'C19'

print(covid)

['C19' 'No' 'C19' 'No' 'C19' 'No']


In [47]:
Cov19 = np.array(['Yes', 'No', 'Yes', 'No', 'Yes', 'No'])

Cov19[Cov19 == 'Yes'] = 'C19'
Cov19[Cov19 == 'No'] = 'Not'

print(Cov19)

['C19' 'Not' 'C19' 'Not' 'C19' 'Not']


In [48]:
notas = np.array([6.8, 4.8, 7.8 , 5.7, 9.1, 5.6, 3.2])
mask_notas = notas > 8

print(mask_notas) # Dados Booleanos conforme cada item da Array
print(notas[mask_notas]) # Resulta em somente aos itens que correspondem aos critérios

[False False False False  True False False]
[9.1]


In [57]:
# Exercicio:

notas_School = np.array([6.8, 4.8, 7.8 , 5.7, 9.1, 5.6, 3.2, 6.5, 8.3, 7.3])

mask_pos = notas_School >= 8 # Abordagem 1 (mesma finalidade)
mask_neg = [notas < 8 for notas in notas_School] # Abordagem 2 (mesma finalidade)

print(f"Notas aprovadas: {notas_School[mask_pos]}")
print(f"Notas reprovadas: {notas_School[mask_neg]}")

Notas aprovadas: [9.1 8.3]
Notas reprovadas: [6.8 4.8 7.8 5.7 5.6 3.2 6.5 7.3]
